version: "3"
services:
  nginx-proxy:
    image: nginx:latest
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: nginx-proxy
    volumes:
      - ../../../config/web-server/nginx/php/conf.d/:/etc/nginx/conf.d/
      - ../../../config/web-server/nginx/php/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../../config/web-server/nginx/php/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../../ssl:/etc/nginx/ssl/
      - ../../../log/nginx/:/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - openproject

  openproject:
    image: openproject/community:11
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    container_name: openproject
    privileged: true
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - "8080"
    environment:
      EMAIL_DELIVERY_METHOD: ${EMAIL_DELIVERY_METHOD}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: "${SMTP_DOMAIN}"
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: "${SMTP_ENABLE_STARTTLS_AUTO}"
      SMTP_USER_NAME: "${SMTP_USER_NAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      TZ: "Asia/Seoul"
      PASSENGER_START_TIMEOUT: ${PASSENGER_START_TIMEOUT}
    restart: always
