version: "3"
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ../../../config/web-server/nginx/php/conf.d/:/etc/nginx/conf.d/
      - ../../../config/web-server/nginx/php/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../../config/web-server/nginx/php/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../../nginx_cache/:/etc/nginx/cache/
      - ../../../ssl:/etc/nginx/ssl/
      - ../../../log/nginx/:/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - openproject
      
  openproject:
    image: openproject/community:10
    container_name: openproject
    environment:
      EMAIL_DELIVERY_METHOD: smtp
      SMTP_ADDRESS: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_DOMAIN: "domain"
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_USER_NAME: "id"
      SMTP_PASSWORD: "api key"
    volumes:
      - ./pgdata/:/var/openproject/pgdata/
      - ../../../log/supervisor/:/var/log/supervisor/
      - ./static/:/var/openproject/assets/
    expose:
      - "8080"
    environment:
      TZ: "Asia/Seoul"
    restart: always


