version: "3"
services:
  webserver:
    build: ../../../docker/nginx/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: nginx-php-webserver
    volumes:
      - ../../../www:/www
      - ../../../script/:/script/
      - ../../../config/web-server/nginx/php/conf.d/:/etc/nginx/conf.d/
      - ../../../config/web-server/nginx/php/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../../config/web-server/nginx/php/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
      - ../../../ssl/certs/:/etc/ssl/certs/
      - ../../../ssl/letsencrypt:/etc/letsencrypt/
      - ../../../log:/log
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Seoul"
    restart: always

  php-app:
    build: ../../../docker/php-fpm/
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: php-app
    volumes:
      - ../../../www:/www
      - ../../../config/app-server/php/pool.d/:/etc/php/7.3/fpm/pool.d
      - ../../../config/app-server/php/php_ini/php.ini:/etc/php/7.3/fpm/php.ini
      - ../../../log:/log
    environment:
      TZ: "Asia/Seoul"
    restart: always
