version: "3"
services:
  gitolite:
    build: ../../../docker/gitolite
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    working_dir: /application
    container_name: gitolite
    volumes:
      - ./storage:/home/gitolite-creator/repositories        
    ports:        
      - "2222:22"
    environment:
      TZ: "Asia/Seoul"    
    restart: always

