version: "3"
services:
  gitolite:
    build: ../../../docker/gitolite
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-file: "${LOG_OPT_MAXF}"
        max-size: "${LOG_OPT_MAXS}"
    working_dir: /application
    container_name: gitolite
    volumes:
      - ./storage:/home/gitolite-creator/repositories
    ports:
      - "2222:22"
    environment:
      TZ: "Asia/Seoul"
    restart: always

