[tool.poetry]
name = "django-sample"
version = "0.1.0"
description = ""
authors = ["bluebamus <bluebamus@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.4"
django = "^5.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
