#!/bin/bash

cd project_path

requirements_file="requirements.txt"

if [ -f $requirements_file ]; then
        echo $requirements_file "is exists."
        pip install -r requirements.txt
fi

gunicorn --workers 4 --bind 0.0.0.0:8000 project_name.wsgi:application --daemon --reload

while true; 
do 
    echo "still live"; 
    sleep 6000; 
done
